---
- hosts: kungekasen
  sudo: yes
  tasks:
    - locale_gen: name=sv_SE.UTF-8 state=present
    - name: Set timezone variables
      copy: content='CET\n'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
    - name: install packages
      apt: name={{ item}} update_cache=yes state=latest
      with_items:
        - apache2
        - git
        - libapache2-mod-php5
    - name: enabled apache2 mods
      apache2_module: name={{ item }} state=present
      notify:
        - restart apache2
      with_items:
        - rewrite
        - php5
    - name: ssh_known_hosts
      copy: src=files/ssh_known_hosts dest=/etc/ssh/
    - name: install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer
    - include: tasks/composerdomain.yaml
               domain=brollop.kungekasen.se
               name=kungekasen
    - include: tasks/composerdomain.yaml
               domain=podcast.kungekasen.se
               name=podcastFeed
    ## monday 1, tuesday 2, wednesday 3 thursday 4, friday 5, saturday 6, sunday 0
    - cron: name="p3popular part 2 måndag till torsdag" minute="0" hour="2" weekday="2-5"
            user=www-data
            job="nice -n19 /var/www/podcastFeed/downloadP3Popular.sh 2 >> /tmp/log 2>> /tmp/log2"
    - cron: name="p3popular fredag" minute="0" hour="2" weekday="6"
            user=www-data
            job="nice -n19 /var/www/podcastFeed/downloadP3Popular.sh 1 >> /tmp/log 2>> /tmp/log2"
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
