---
- hosts: kungekasen
  sudo: yes
  tasks:
    - locale_gen: name=sv_SE.UTF-8 state=present
    - name: Set timezone variables
      copy: content='CET\n'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
    - name: install packages
      apt: name={{ item}} update_cache=yes state=latest
      with_items:
        - apache2
        - git
        - libapache2-mod-php5
        - spamassassin
        - spamc
        - maildrop
    - name: enabled apache2 mods
      apache2_module: name={{ item }} state=present
      notify:
        - restart apache2
      with_items:
        - rewrite
        - php5
        - ssl
    - name: ssh_known_hosts
      copy: src=files/ssh_known_hosts dest=/etc/ssh/
    - name: aliases
      copy: src=files/aliases dest=/etc/aliases
      notify: newaliases
    - name: install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer
    - include: tasks/composerdomain.yaml
               domain=brollop.kungekasen.se
               name=kungekasen
    - include: tasks/composerdomain.yaml
               domain=podcast.kungekasen.se
               name=podcastFeed
    ## monday 1, tuesday 2, wednesday 3 thursday 4, friday 5, saturday 6, sunday 0
    - cron: name="p3popular part 2 måndag till torsdag" minute="0" hour="7" weekday="2-5"
            user=www-data
            job="nice -n19 /var/www/podcastFeed/downloadP3Popular.sh 2 >> /tmp/log 2>> /tmp/log2"
    - cron: name="clear tmp every night for older than 14 days" minute="0" hour="2"
            user=root
            job="sudo find /tmp -ctime +14 -exec rm -rf {} +"
    - user: name=christian groups=adm,sudo
    - include: tasks/virtualhost.yaml
               domain=kungekasen.se
               name=kungekasen.se
    - group: name=spamd
    - user: name=spamd groups=spamd home=/var/log/spamassassin shell=/bin/false
    - name: spamassassin enabled           
      lineinfile:
        dest: /etc/default/spamassassin
        regexp: '^ENABLED='
        line: 'ENABLED=1'
    - name: spamassassin cron
      lineinfile:
        dest: /etc/default/spamassassin
        regexp: '^CRON='
        line: 'CRON=1'
    - name: spamassassin options
      lineinfile:
        dest: /etc/default/spamassassin
        regexp: '^OPTIONS='
        line: 'OPTIONS="--create-prefs --max-children 2 --username spamd \
        -H /var/log/spamassassin -s /var/log/spamassassin/spamd.log"'
    - name: spamassassin local.cf
      copy: src=files/local.cf dest=/etc/spamassassin/
      notify:
        - restart spamassassin
    - name: maildrop su-bit
      file:
        dest: /usr/bin/maildrop
        state: touch
        mode: "2755"
    - name: maildrop conf 
      copy: src=files/maildroprc dest=/etc/
    ## FIXME does not create the file
    - name: maildrop log
      file:
        dest: /var/log/maildrop.log
        state: touch
        owner: root
        group: mail
        mode: "660"
    #- name: create empty imapd ssl
    #  local_action: "shell > /etc/courier/imapd.pem"
    #- name: concat keys to courier
    #  local_action: "shell echo {{ item }} >> /etc/courier/imapd.pem"
    #  with_file:
    #    - /etc/letsencrypt/live/kungekasen.se/privkey.pem
    #    - /etc/letsencrypt/live/kungekasen.se/fullchain.pem
    ## cat /etc/letsencrypt/live/kungekasen.se/privkey.pem \
    ## /etc/letsencrypt/live/kungekasen.se/fullchain.pem > /etc/courier/imapd.pem
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart spamassassin
      service: name=spamassassin state=restarted
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
    - name: newaliases
      command: newaliases
  vars:
    - filesystems_ro_rootfs_enable: false
    - courier_esmtpd_enable: false
    - courier_home_mailbox: Maildir/
    - postfix_myhostname: kungekasen.se
    - postfix_mydestination: $myhostname, localhost.$mydomain, localhost, sipola.se, kungekasen.com
    - postfix_inet_interfaces: all
    - postfix_smtpd_use_tls: yes
    - postfix_smtp_sasl_auth_enable: yes
  roles:
    #https://github.com/goetzk/ansible-courier  
    - { role: goetzk.courier, courier_esmtpd_enable: false, courier_imap_enable: true }
    #https://github.com/Stouts/Stouts.postfix
    - Stouts.postfix

