---
## do not forget to add private ssh key 
- name: git repo
  git: repo=git@github.com:christiansipola/{{ name }}.git 
       dest=/var/www/{{ name }}
       key_file=/home/christian/.ssh/id_rsa
- name: www permissions
  file:
    path: /var/www/{{ name }}
    owner: www-data
    group: www-data
    recurse: true

- name: run composer
  composer:
    command: install
    working_dir: /var/www/{{ name }}
    sudo_user: www-data
- name: create virtual host
  copy: src=virtualhosts/{{ domain }}.conf
        dest=/etc/apache2/sites-available/
- name: a2ensite {{ domain }}
  command: a2ensite {{ domain }}
  notify:
    - restart apache2
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}.conf
