---
- name: create virtual host
  copy: src=virtualhosts/{{ domain }}.conf
        dest=/etc/apache2/sites-available/
- name: a2ensite {{ domain }}
  command: a2ensite {{ domain }}
  notify:
    - restart apache2
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}.conf